package actions

import kotlinx.serialization.serializer
import runtime.ActionRegistry

/** Registers all built-in (non-intent) actions. Keep in sync with smoke-test registry. */
fun ActionRegistry.registerBuiltinActions() {
    register(
        "device_info",
        DeviceInfoAction(),
        serializer<DeviceInfoInput>(),
        serializer<DeviceInfoOutput>(),
    )
    register(
        "system_info",
        SystemInfoAction(),
        serializer<SystemInfoInput>(),
        serializer<SystemInfoOutput>(),
    )
    register(
        "network_status",
        NetworkStatusAction(),
        serializer<NetworkStatusInput>(),
        serializer<NetworkStatusOutput>(),
    )
    register(
        "power_status",
        PowerStatusAction(),
        serializer<PowerStatusInput>(),
        serializer<PowerStatusOutput>(),
    )
    register(
        "set_volume",
        SetVolumeAction(),
        serializer<SetVolumeInput>(),
        serializer<SetVolumeOutput>(),
    )
    register(
        "set_silent_mode",
        SetSilentModeAction(),
        serializer<SetSilentModeInput>(),
        serializer<SetSilentModeOutput>(),
    )
    register(
        "storage_info",
        StorageInfoAction(),
        serializer<StorageInfoInput>(),
        serializer<StorageInfoOutput>(),
    )
    register(
        "get_location",
        LocationAction(),
        serializer<LocationInput>(),
        serializer<LocationOutput>(),
    )
    register(
        "foreground_app",
        ForegroundAppAction(),
        serializer<ForegroundAppInput>(),
        serializer<ForegroundAppOutput>(),
    )
    register(
        "list_installed_apps",
        ListInstalledAppsAction(),
        serializer<ListInstalledAppsInput>(),
        serializer<ListInstalledAppsOutput>(),
    )
    register(
        "launch_app",
        LaunchAppAction(),
        serializer<LaunchAppInput>(),
        serializer<LaunchResult>(),
    )
    register(
        "set_alarm",
        SetAlarmAction(),
        serializer<SetAlarmInput>(),
        serializer<LaunchResult>(),
    )
    register(
        "set_timer",
        SetTimerAction(),
        serializer<SetTimerInput>(),
        serializer<LaunchResult>(),
    )
    register(
        "list_alarms",
        ShowAlarmsAction(),
        serializer<ShowAlarmsInput>(),
        serializer<LaunchResult>(),
    )
    register(
        "read_sms",
        ReadSmsAction(),
        serializer<ReadSmsInput>(),
        serializer<ReadSmsOutput>(),
    )
    register(
        "send_sms",
        SendSmsAction(),
        serializer<SendSmsInput>(),
        serializer<SendSmsOutput>(),
    )
    register(
        "read_call_log",
        ReadCallLogAction(),
        serializer<ReadCallLogInput>(),
        serializer<ReadCallLogOutput>(),
    )
    register(
        "place_call",
        PlaceCallAction(),
        serializer<PlaceCallInput>(),
        serializer<PlaceCallOutput>(),
    )
    register(
        "search_contacts",
        SearchContactsAction(),
        serializer<SearchContactsInput>(),
        serializer<SearchContactsOutput>(),
    )
    register(
        "list_notifications",
        ListNotificationsAction(),
        serializer<ListNotificationsInput>(),
        serializer<ListNotificationsOutput>(),
    )
    register(
        "clipboard_copy",
        ClipboardCopyAction(),
        serializer<ClipboardCopyInput>(),
        serializer<ClipboardCopyOutput>(),
    )
    register(
        "clipboard_read",
        ClipboardReadAction(),
        serializer<ClipboardReadInput>(),
        serializer<ClipboardReadOutput>(),
    )
    register(
        "wifi_toggle",
        WifiToggleAction(),
        serializer<WifiToggleInput>(),
        serializer<WifiToggleOutput>(),
    )
    register(
        "bluetooth_toggle",
        BluetoothToggleAction(),
        serializer<BluetoothToggleInput>(),
        serializer<BluetoothToggleOutput>(),
    )
    register(
        "media_play_pause",
        MediaPlayPauseAction(),
        serializer<MediaPlayPauseInput>(),
        serializer<MediaPlayPauseOutput>(),
    )
    register(
        "media_now_playing",
        NowPlayingAction(),
        serializer<NowPlayingInput>(),
        serializer<NowPlayingOutput>(),
    )
    register(
        "screenshot",
        ScreenshotAction(),
        serializer<ScreenshotInput>(),
        serializer<ScreenshotOutput>(),
    )
    register(
        "screen_record",
        ScreenRecordAction(),
        serializer<ScreenRecordInput>(),
        serializer<ScreenRecordOutput>(),
    )
    register(
        "take_photo",
        TakePhotoAction(),
        serializer<TakePhotoInput>(),
        serializer<TakePhotoOutput>(),
    )
    register(
        "record_video",
        RecordVideoAction(),
        serializer<RecordVideoInput>(),
        serializer<RecordVideoOutput>(),
    )
    register(
        "record_audio",
        RecordAudioAction(),
        serializer<RecordAudioInput>(),
        serializer<RecordAudioOutput>(),
    )
    register(
        "open_webpage",
        OpenWebPageAction(),
        serializer<OpenWebPageInput>(),
        serializer<OpenWebPageOutput>(),
    )
    register(
        "select_file",
        SelectFileAction(),
        serializer<SelectFileInput>(),
        serializer<SelectFileOutput>(),
    )
    register(
        "search_files",
        FileSearchAction(),
        serializer<FileSearchInput>(),
        serializer<FileSearchOutput>(),
    )
    register(
        "list_calendar_events",
        ListCalendarEventsAction(),
        serializer<ListCalendarEventsInput>(),
        serializer<ListCalendarEventsOutput>(),
    )
    register(
        "create_calendar_event",
        InsertCalendarEventAction(),
        serializer<InsertCalendarEventInput>(),
        serializer<InsertCalendarEventOutput>(),
    )
    register(
        "check_permissions",
        PermissionStatusAction(),
        serializer<PermissionStatusInput>(),
        serializer<PermissionStatusOutput>(),
    )
    register(
        "read_file",
        ReadFileAction(),
        serializer<ReadFileInput>(),
        serializer<ReadFileOutput>(),
    )
    register(
        "http_call",
        HttpCallAction(),
        serializer<HttpRequest>(),
        serializer<HttpResponse>(),
    )
}
