[package]
name = "dispatcher"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
async-trait = "0.1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
actions = { path = "../actions" }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
base64 = "0.22"
serde_json = "1"

[dev-dependencies]
serde_json = "1"
